core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('', include('simpleapp.urls', namespace='simple_app')),
]

simpleapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from simpleapp import views

app_name = 'simple_app'
urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('', views.index, name='index'),
]

simpleapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from simpleapp.managers import SimpleUserManager


class SimpleUser(AbstractUser):
    username = models.CharField('username', max_length=100)
    email = models.EmailField('email address', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = SimpleUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name

simpleapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class SingUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200, required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'checkin-form__input'
            visible.field.widget.attrs['placeholder'] = ' '


class SimpleUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ('email',)


class SimpleUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email',)

simpleapp/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from simpleapp.forms import SingUpForm


def sign_up(request):
    if request.method == "POST":
        form = SingUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect('simple_app:index')
    else:
        form = SingUpForm()
    return render(request, 'registration/signup-page.html', {'form': form})


@login_required(login_url='simple_app:sign_up')
def index(request):
    return render(request, 'home-page.html')

simpleapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap&subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="wrapper">
        {% block content %}

        {% endblock %}
    </div>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

simpleapp/templates/home-page.html
{% extends 'base.html' %}

{% block title %}Home page{% endblock %}

{% block content %}
    <section class="content">
        <div class="content__wrapper">
            <h1>Home page</h1>
            <p>{{ user.last_name }} {{ user.first_name }}</p>
            <a href="{% url 'simple_app:logout' %}"> logout</a>
        </div>
    </section>
{% endblock %}